# This code examines the dataset that is accompanying Oreilly's:
# modern-analytics-excel-book
# I am using ch1 examples, data in others folder.
# https://github.com/stringfestdata/modern-analytics-excel-book/tree/main
# The code below was generated by ChatGPT

# Load necessary library
library(stats4)
library(readxl)

# Check were is the current execution directory.
getwd()

# Set current working directory
setwd("G:\\My Drive\\Current\\0-datascience_with_r\\r_course_code_project\\experiments\\log_normal_mle")

# Assuming 'data' is your vector of grocery spending amounts
# data <- c(...)

# Replace 'path_to_file.xlsx' with the actual path to your Excel file
data_frame <- read_excel('ch_01_dummy.xlsx')

# To specify a sheet by name or index
# data <- read_excel("path_to_file.xlsx", sheet = "Sheet1")
# To specify a range
# data <- read_excel("path_to_file.xlsx", range = "Sheet1!A1:D100")


spending_data <- data_frame$grocery

# Check if spending_data contains only positive values
if(any(spending_data <= 0)) {
  stop("Data contains non-positive values which cannot be log-transformed")
}

# # Define the negative log-likelihood function for a log-normal distribution
# neg_log_likelihood <- function(params) {
#   # params[1] is 'meanlog' and params[2] is 'sdlog' for the log-normal distribution
#   -sum(dlnorm(spending_data, meanlog=params[1], sdlog=params[2], log=TRUE))
# }

# Define the negative log-likelihood function for a log-normal distribution
neg_log_likelihood <- function(meanlog, sdlog) {
  -sum(dlnorm(spending_data, meanlog = meanlog, sdlog = sdlog, log = TRUE))
}


# Initial parameter estimates
start_params <- c(meanlog=mean(log(spending_data)), sdlog=sd(log(spending_data)))

# Print the length of spending_data and start_params for debugging
print(paste("Length of spending_data:", length(spending_data)))
print(paste("Start parameters:", start_params))
print(paste("Length of start_params:", length(start_params)))
  
if(length(start_params) != 2) {
  stop("Start parameter vector has incorrect length")
}

# Explicitly name the start parameters
names(start_params) <- c("meanlog", "sdlog")

# Perform the optimization using MLE
mle_result <- mle(neg_log_likelihood, start=start_params, method="L-BFGS-B")

# Extract the estimated parameters
estimated_params <- coef(mle_result)
names(estimated_params) <- c("meanlog", "sdlog")

# Output the estimated parameters
print(paste("Estimated parameters" ,estimated_params))
