# Generated by ChatGPT 3.5


# Sample data
x <- c(1, 2, 3, 4, 5)
y <- c(10, 8, 6, 4, 2)

# Create a scatter plot
plot(x, y, type = "p", col = "blue", main = "Scatter Plot", xlab = "X-axis", ylab = "Y-axis")

# Adding different elements and annotations

# 1. Points (highlight specific data points)
points(3, 6, col = "red", pch = 19)  # Add a red point at (3, 6)

# 2. Text Labels (add labels or annotations)
text(2, 9, "Point (2, 9)", col = "green")  # Add text label at (2, 9)

# 3. Arrows (indicate direction or highlight)
arrows(4, 8, 5, 7, col = "purple", length = 0.1)  # Add a purple arrow

# 4. Rectangles (highlight a region of interest)
rect(1.5, 2, 2.5, 9, border = "orange", lty = 2)  # Add an orange dashed rectangle

# 5. Legends (explain plot elements)
legend("topright", legend = "Legend", col = c("red", "green", "purple", "orange"), 
       pch = c(19, NA, NA, NA), lty = c(NA, NA, 1, 2), 
       title = "Key", bg = "white")

# 6. Grid Lines (customize grid)
abline(h = c(3, 6, 9), col = "gray", lty = 2)  # Add horizontal dashed grid lines

# 7. Shapes and Polygons (create shapes)
polygon(c(2, 2.5, 3), c(8, 9, 8), col = "pink")  # Add a pink polygon

# 8. Error Bars (represent data variability)
segments(x0 = x - 0.1, y0 = y, x1 = x + 0.1, y1 = y, col = "brown")  # Add brown error bars

# Points are added using the points function to highlight specific data points.
# Text labels are added with the text function to annotate the plot.
# An arrow is created using the arrows function.
# A rectangle is drawn using the rect function to highlight a region of interest.
# A legend is added to explain plot elements.
# Dashed grid lines are customized using abline to enhance the grid appearance.
# A pink polygon is created using the polygon function.
# Error bars are represented by adding small line segments using the segments function.
